### ISSUE TITLE
Add support for similar / undef initializer

### ISSUE THREAD

**Issue by piever** [queryverse/DataValues.jl#53]
`similar(DataValueArray{T}, n)` falls back to `DataValueArray{T}(undef, n)` which errors. Would it be OK to simply define it as the `DataValueArray` of size `n` where all the data is missing?

**Comment by davidanthoff** [comment]
We should probably just add the ``undef`` constructor that has everything missing, right?

The whole ``DataValueArray`` story is not in super great shape right now, there are various parts that I haven't properly migrated to julia 1.0 style. Any help/PRs would be most welcome!

**Comment by piever** [comment]
Yes, I think that should be enough: I've made a PR here https://github.com/queryverse/DataValues.jl/pull/54

**Comment by davidanthoff** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/20706
